<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Actual {
	private $actual_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'actual_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'actual_page_init' ) );
	}

	public function actual_add_plugin_page() {
		add_options_page(
			'Actual', // page_title
			'Actual', // menu_title
			'manage_options', // capability
			'actual', // menu_slug
			array( $this, 'actual_create_admin_page' ) // function
		);
	}

	public function actual_create_admin_page() {
		$this->actual_options = get_option( 'actual_option_name' ); ?>

		<div class="wrap">
			<h2>Actual</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'actual_option_group' );
					do_settings_sections( 'actual-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function actual_page_init() {
		register_setting(
			'actual_option_group', // option_group
			'actual_option_name', // option_name
			array( $this, 'actual_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'actual_setting_section', // id
			'Settings', // title
			array( $this, 'actual_section_info' ), // callback
			'actual-admin' // page
		);

		add_settings_field(
			'ftp_host_0', // id
			'FTP Host', // title
			array( $this, 'ftp_host_0_callback' ), // callback
			'actual-admin', // page
			'actual_setting_section' // section
		);

		add_settings_field(
			'ftp_port_1', // id
			'FTP Port', // title
			array( $this, 'ftp_port_1_callback' ), // callback
			'actual-admin', // page
			'actual_setting_section' // section
		);

		add_settings_field(
			'ftp_username_2', // id
			'FTP Username', // title
			array( $this, 'ftp_username_2_callback' ), // callback
			'actual-admin', // page
			'actual_setting_section' // section
		);

		add_settings_field(
			'ftp_password_3', // id
			'FTP Password', // title
			array( $this, 'ftp_password_3_callback' ), // callback
			'actual-admin', // page
			'actual_setting_section' // section
		);

		add_settings_field(
			'ftp_path_4', // id
			'FTP Path', // title
			array( $this, 'ftp_path_4_callback' ), // callback
			'actual-admin', // page
			'actual_setting_section' // section
		);
	}

	public function actual_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['ftp_host_0'] ) ) {
			$sanitary_values['ftp_host_0'] = sanitize_text_field( $input['ftp_host_0'] );
		}

		if ( isset( $input['ftp_port_1'] ) ) {
			$sanitary_values['ftp_port_1'] = sanitize_text_field( $input['ftp_port_1'] );
		}

		if ( isset( $input['ftp_username_2'] ) ) {
			$sanitary_values['ftp_username_2'] = sanitize_text_field( $input['ftp_username_2'] );
		}

		if ( isset( $input['ftp_password_3'] ) ) {
			$sanitary_values['ftp_password_3'] = sanitize_text_field( $input['ftp_password_3'] );
		}

		if ( isset( $input['ftp_path_4'] ) ) {
			$sanitary_values['ftp_path_4'] = sanitize_text_field( $input['ftp_path_4'] );
		}

		return $sanitary_values;
	}

	public function actual_section_info() {
		
	}

	public function ftp_host_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="actual_option_name[ftp_host_0]" id="ftp_host_0" value="%s">',
			isset( $this->actual_options['ftp_host_0'] ) ? esc_attr( $this->actual_options['ftp_host_0']) : ''
		);
	}

	public function ftp_port_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="actual_option_name[ftp_port_1]" id="ftp_port_1" value="%s">',
			isset( $this->actual_options['ftp_port_1'] ) ? esc_attr( $this->actual_options['ftp_port_1']) : ''
		);
	}

	public function ftp_username_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="actual_option_name[ftp_username_2]" id="ftp_username_2" value="%s">',
			isset( $this->actual_options['ftp_username_2'] ) ? esc_attr( $this->actual_options['ftp_username_2']) : ''
		);
	}

	public function ftp_password_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="actual_option_name[ftp_password_3]" id="ftp_password_3" value="%s">',
			isset( $this->actual_options['ftp_password_3'] ) ? esc_attr( $this->actual_options['ftp_password_3']) : ''
		);
	}

	public function ftp_path_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="actual_option_name[ftp_path_4]" id="ftp_path_4" value="%s">',
			isset( $this->actual_options['ftp_path_4'] ) ? esc_attr( $this->actual_options['ftp_path_4']) : ''
		);
	}

}
if ( is_admin() )
	$actual = new Actual();

/* 
 * Retrieve this value with:
 * $actual_options = get_option( 'actual_option_name' ); // Array of All Options
 * $ftp_host_0 = $actual_options['ftp_host_0']; // FTP Host
 * $ftp_port_1 = $actual_options['ftp_port_1']; // FTP Port
 * $ftp_username_2 = $actual_options['ftp_username_2']; // FTP Username
 * $ftp_password_3 = $actual_options['ftp_password_3']; // FTP Password
 * $ftp_path_4 = $actual_options['ftp_path_4']; // FTP Path
 */